In [1]:
import pandas as pd
pd.set_option('display.max_columns', None)
import datetime
import numpy as np
from sklearn import preprocessing 
from sqlalchemy.engine.base import Engine
from sqlalchemy import create_engine
import psycopg2
engine = create_engine('postgresql://lhl_student:lhl_student@mid-term-project.ca2jkepgjpne.us-east-2.rds.amazonaws.com:5432/mid_term_project')
df = pd.read_sql_query('select * from flights limit 2000000', engine)

/usr/local/lib/python3.7/dist-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)


In [2]:
print(df.columns)

Index(['fl_date', 'mkt_unique_carrier', 'branded_code_share', 'mkt_carrier',
       'mkt_carrier_fl_num', 'op_unique_carrier', 'tail_num',
       'op_carrier_fl_num', 'origin_airport_id', 'origin', 'origin_city_name',
       'dest_airport_id', 'dest', 'dest_city_name', 'crs_dep_time', 'dep_time',
       'dep_delay', 'taxi_out', 'wheels_off', 'wheels_on', 'taxi_in',
       'crs_arr_time', 'arr_time', 'arr_delay', 'cancelled',
       'cancellation_code', 'diverted', 'dup', 'crs_elapsed_time',
       'actual_elapsed_time', 'air_time', 'flights', 'distance',
       'carrier_delay', 'weather_delay', 'nas_delay', 'security_delay',
       'late_aircraft_delay', 'first_dep_time', 'total_add_gtime',
       'longest_add_gtime', 'no_name'],
      dtype='object')


In [3]:
dfF = df[['fl_date', 'mkt_unique_carrier', 'branded_code_share', 'mkt_carrier',
       'mkt_carrier_fl_num', 'op_unique_carrier', 'tail_num',
       'op_carrier_fl_num', 'origin_airport_id', 'origin', 'origin_city_name',
       'dest_airport_id', 'dest', 'dest_city_name', 'crs_dep_time','dep_delay',
       'crs_arr_time', 'dup', 'crs_elapsed_time', 'flights', 'distance','arr_delay','carrier_delay', 'weather_delay', 'nas_delay', 'security_delay',
       'late_aircraft_delay','cancelled','taxi_in', 'taxi_out','diverted']].copy()

In [4]:
total = dfF.isnull().sum().sort_values(ascending=False)
percent = (dfF.isnull().sum()/dfF.isnull().count()).sort_values(ascending=False)
missing_data = pd.concat([total, percent], axis=1, keys=['Total', 'Percent'])
missing_data

Total   Percent
late_aircraft_delay  1593560  0.796780
security_delay       1593560  0.796780
nas_delay            1593560  0.796780
weather_delay        1593560  0.796780
carrier_delay        1593560  0.796780
arr_delay              50903  0.025451
taxi_in                46645  0.023322
taxi_out               45579  0.022790
dep_delay              44306  0.022153
tail_num                8873  0.004437
crs_arr_time               0  0.000000
cancelled                  0  0.000000
distance                   0  0.000000
flights                    0  0.000000
crs_elapsed_time           0  0.000000
dup                        0  0.000000
fl_date                    0  0.000000
mkt_unique_carrier         0  0.000000
crs_dep_time               0  0.000000
dest_city_name             0  0.000000
dest                       0  0.000000
dest_airport_id            0  0.000000
origin_city_name           0  0.000000
origin                     0  0.000000
origin_airport_id          0  0.000000
op_carrier_fl_num          0  0.000000
op_unique_carrier          0  0.000000
mkt_carrier_fl_num         0  0.000000
mkt_carrier                0  0.000000
branded_code_share         0  0.000000
diverted                   0  0.000000

In [5]:
delaytypes = ['carrier_delay', 'weather_delay', 'nas_delay', 'security_delay', 'late_aircraft_delay']
for delay in delaytypes:
    dfF['is'+delay] = np.where((dfF[delaytypes].idxmax(axis=1) == delay)&(dfF[delay]>0), 1, 0)

In [6]:
dfF['delay_type'] = df[delaytypes].idxmax(axis="columns")


In [7]:
delay_dict = {'carrier_delay':1, 'weather_delay':2, 'nas_delay':3, 'security_delay':4, 'late_aircraft_delay':5}
dfF['delay_type'] = dfF['delay_type'].map(delay_dict)

In [8]:
dfF['flight_number'] = dfF['mkt_unique_carrier']+dfF['mkt_carrier_fl_num'].astype(str)

In [9]:
dfF['flight_number'].value_counts()

AS64      440
AS65      440
AS55      360
AS62      360
AS61      349
         ... 
AS1816      1
AA3288      1
AA1087      1
UA2428      1
G41641      1
Name: flight_number, Length: 31544, dtype: int64

In [11]:
print('Number of different flight_numbers in train set : ' +str(len(dfF['flight_number'].value_counts())))

Number of different flight_numbers in train set : 31544


In [12]:
dfF.flights.describe()

count    2000000.0
mean           1.0
std            0.0
min            1.0
25%            1.0
50%            1.0
75%            1.0
max            1.0
Name: flights, dtype: float64

In [13]:
dfF.fl_date = pd.to_datetime(dfF.fl_date, format='%Y-%m-%d')

dfF['fl_month'] = pd.DatetimeIndex(dfF.fl_date).month
dfF['fl_day'] = pd.DatetimeIndex(dfF.fl_date).day
dfF['fl_day_of_year'] = dfF.fl_date.dt.dayofyear
dfF['fl_day_of_week'] = dfF.fl_date.dt.dayofweek

dfF['crs_dep_time'] = dfF['crs_dep_time'].apply(lambda x: '{0:0>4}'.format(x))
dfF['crs_arr_time'] = dfF['crs_arr_time'].apply(lambda x: '{0:0>4}'.format(x))

dfF['dep_hour'] = dfF['crs_dep_time'].str[:2]
dfF['arr_hour'] = dfF['crs_arr_time'].str[:2]

In [14]:
# duration type (eg short, med, long haul)
bins = [-100, 180, 360, 2000]
labels = [1,2,3]
dfF['duration_type'] = pd.cut(dfF['crs_elapsed_time'], bins=bins, labels=labels)

In [15]:
hour_to_daysection = {'00': 0,
                      '01': 0,
                      '02': 0,
                      '03': 0,
                      '04': 0,
                      '05': 0,
                      '06': 1,
                      '07': 1,
                      '08': 1,
                      '09': 1,
                      '10': 1,
                      '11': 2,
                      '12': 2,
                      '13': 2,
                      '14': 2,
                      '15': 2,
                      '16': 2,
                      '17': 3,
                      '18': 3,
                      '19': 3,
                      '20': 4,
                      '21': 4,
                      '22': 4,
                      '23': 4,
                      '24': 4}

# Night = 0, Morning rush = 1, Midday = 2, Afternoon rush = 3, Evening = 4

dfF['dep_daysection'] = dfF['dep_hour'].map(hour_to_daysection)

dfF['arr_daysection'] = dfF['arr_hour'].map(hour_to_daysection)

In [16]:
month_to_season = {1: 1, 2: 1, 3: 2, 4: 2, 5: 2, 6: 3, 7: 3, 8: 3, 9: 4, 10: 4, 11: 4, 12: 1}
dfF['fl_season'] = dfF['fl_month'].map(month_to_season)

In [17]:
dfF['origin_state'] = dfF['origin_city_name'].str[-2:]
dfF['dest_state'] = dfF['dest_city_name'].str[-2:]

In [18]:
# total volume at origin and dest airport
dfF['origin_airport_vol'] = dfF.groupby(['origin_airport_id'])['flights'].transform(np.sum)
dfF['dest_airport_vol'] = dfF.groupby(['origin_airport_id'])['flights'].transform(np.sum)

# how much the airline operates out of that airport
dfF['carrier_origin_apt_vol'] = dfF.groupby(['origin_airport_id','op_unique_carrier'])['flights'].transform(np.sum)
dfF['carrier_dest_apt_vol'] = dfF.groupby(['dest_airport_id','op_unique_carrier'])['flights'].transform(np.sum)

# how much the airline operates out of that airport as pct
dfF['carrier_origin_apt_pct'] = dfF['carrier_origin_apt_vol'] / dfF['origin_airport_vol'] * 100
dfF['carrier_dest_apt_pct'] = dfF['carrier_dest_apt_vol'] / dfF['dest_airport_vol'] * 100

In [19]:
dfF['mean_carrier_arr_delay'] = dfF.groupby(['op_unique_carrier'])['arr_delay'].transform(np.mean)


In [22]:
stattype = [('mean', np.mean), ('median', np.median), ('std',np.std)]

for stat in stattype:
  # arr per airline per month
  dfF[stat[0]+'_carrier_arr_delay_month'] = dfF.groupby(['op_unique_carrier','fl_month'])['arr_delay'].transform(stat[1])

  # dep per airline per month
  dfF[stat[0]+'_carrier_dep_delay_month'] = dfF.groupby(['op_unique_carrier','fl_month'])['dep_delay'].transform(stat[1])


In [23]:
## Mean Carrier-Airport-(DEP and ARR) delay per (DEP and ARR) hour

stattype = [('mean', np.mean), ('median', np.median), ('std',np.std)]

for stat in stattype:
  dfF[stat[0]+'_carrier_origin_dep-hour_dep_delay'] = dfF.groupby(['op_unique_carrier','origin','dep_hour'])['dep_delay'].transform(stat[1])
  dfF[stat[0]+'_carrier_dest_fl-hour_delay'] = dfF.groupby(['op_unique_carrier','dest','arr_hour'])['arr_delay'].transform(stat[1])


In [24]:
## Mean DEP and ARR delay for Carrier routes per month per day of the week per day section. 

stattype = [('mean', np.mean), ('median', np.median), ('std',np.std)]

for stat in stattype:
  dfF[stat[0]+'_carrier_route_month_dow_dayS_dep-delay'] = dfF.groupby(['op_unique_carrier','origin','dest','fl_month','fl_day_of_week','dep_daysection'])['dep_delay'].transform(stat[1])
  dfF[stat[0]+'_carrier_route_month_dow_dayS_arr-delay'] = dfF.groupby(['op_unique_carrier','origin','dest','fl_month','fl_day_of_week','arr_daysection'])['arr_delay'].transform(stat[1])

In [25]:
#means
stattype = [('mean', np.mean), ('median', np.median), ('std',np.std)]

for stat in stattype:
  #by month
  dfF[stat[0]+'_route_arr_delay_month'] = dfF.groupby(['origin','dest','fl_month'])['arr_delay'].transform(stat[1])
  dfF[stat[0]+'_route_dep_delay_month'] = dfF.groupby(['origin','dest','fl_month'])['dep_delay'].transform(stat[1])
  
  #by day of week
  dfF[stat[0]+'_route_arr_delay_dow'] = dfF.groupby(['origin','dest','fl_day_of_week'])['arr_delay'].transform(stat[1])
  dfF[stat[0]+'_route_dep_delay_dow'] = dfF.groupby(['origin','dest','fl_day_of_week'])['dep_delay'].transform(stat[1])

  #by departure day section
  dfF[stat[0]+'_route_arr_delay_dep_hour'] = dfF.groupby(['origin','dest','dep_daysection'])['arr_delay'].transform(stat[1])
  dfF[stat[0]+'_route_dep_delay_dep_hour'] = dfF.groupby(['origin','dest','dep_daysection'])['dep_delay'].transform(stat[1])

  #by arrival day section
  dfF[stat[0]+'_route_arr_delay_arr_hour'] = dfF.groupby(['origin','dest','arr_daysection'])['arr_delay'].transform(stat[1])
  dfF[stat[0]+'_route_dep_delay_arr_hour'] = dfF.groupby(['origin','dest','arr_daysection'])['dep_delay'].transform(stat[1])


In [26]:
## Origin weather delay per month PCT
dfF['origin_month_weather_delay_pct'] = dfF.groupby(['origin','fl_month'])['isweather_delay'].transform(np.sum) / dfF.groupby(['origin','fl_month'])['flights'].transform(np.sum) * 100
## Dest weather delay per month PCT 
dfF['dest_month_weather_delay_pct'] = dfF.groupby(['dest','fl_month'])['isweather_delay'].transform(np.sum) / dfF.groupby(['dest','fl_month'])['flights'].transform(np.sum) * 100
## Route weather delay per month PCT
dfF['route_month_weather_delay_pct'] = dfF.groupby(['origin','dest','fl_month'])['isweather_delay'].transform(np.sum) / dfF.groupby(['origin','dest','fl_month'])['flights'].transform(np.sum) * 100


In [27]:
#list of each delay type
delaytypes = ['carrier_delay', 'weather_delay', 'nas_delay', 'security_delay', 'late_aircraft_delay']
times = ['arr_daysection', 'dep_daysection']
#creates feature for % of each delay type for time of day
for delay in delaytypes:
  for time in times:
    dfF[time+'_'+delay+'_pct'] = dfF.groupby([time])['is'+delay].transform(np.sum) / dfF.groupby([time])['flights'].transform(np.sum) * 100

#dropping arrival time vs security and late aircraft delay
dfF = dfF.drop(['arr_daysection_security_delay_pct','arr_daysection_late_aircraft_delay_pct'],axis=1)


In [30]:
#list of each delay type
delaytypes = ['carrier_delay', 'weather_delay', 'nas_delay', 'security_delay', 'late_aircraft_delay']

#creates feature for % of each delay type for each carrier
for delay in delaytypes:
    dfF['carrier_'+delay+'_pct'] = dfF.groupby(['op_unique_carrier'])['is'+delay].transform(np.sum) / dfF.groupby(['op_unique_carrier'])['flights'].transform(np.sum) * 100
#list of each delay type
delaytypes = ['carrier_delay', 'late_aircraft_delay']
#creates fields for each delay type
for delay in delaytypes:
    dfF['carrier_route_month_'+delay] = dfF.groupby(['op_unique_carrier','origin','dest','fl_month'])['is'+delay].transform(np.sum) / dfF.groupby(['op_unique_carrier','origin','dest','fl_month'])['flights'].transform(np.sum) * 100


In [31]:
#list of each delay type
delaytypes = ['nas_delay']
#creates fields for each delay type
for delay in delaytypes:
    dfF['origin_month_weekday_daysection_'+delay] = dfF.groupby(['origin','fl_month','fl_day_of_week','dep_daysection'])['is'+delay].transform(np.sum) / dfF.groupby(['origin','fl_month','fl_day_of_week','dep_daysection'])['flights'].transform(np.sum) * 100
for delay in delaytypes:
    dfF['dest_month_weekday_daysection_'+delay] = dfF.groupby(['dest','fl_month','fl_day_of_week','arr_daysection'])['is'+delay].transform(np.sum) / dfF.groupby(['dest','fl_month','fl_day_of_week','arr_daysection'])['flights'].transform(np.sum) * 100
for delay in delaytypes:
    dfF['route_month_weekday_daysection_'+delay] = dfF.groupby(['origin','dest','fl_month','fl_day_of_week','dep_daysection'])['is'+delay].transform(np.sum) / dfF.groupby(['origin','dest','fl_month','fl_day_of_week','dep_daysection'])['flights'].transform(np.sum) * 100

In [32]:
df_dummy = pd.get_dummies(dfF[["op_unique_carrier"]])
df_dummy.shape
# Merge into DF
dfF = pd.concat([dfF,df_dummy],axis=1).drop(["op_unique_carrier",'op_unique_carrier_9E'],axis=1)


In [33]:
list(dfF.columns)

['fl_date',
 'mkt_unique_carrier',
 'branded_code_share',
 'mkt_carrier',
 'mkt_carrier_fl_num',
 'tail_num',
 'op_carrier_fl_num',
 'origin_airport_id',
 'origin',
 'origin_city_name',
 'dest_airport_id',
 'dest',
 'dest_city_name',
 'crs_dep_time',
 'dep_delay',
 'crs_arr_time',
 'dup',
 'crs_elapsed_time',
 'flights',
 'distance',
 'arr_delay',
 'carrier_delay',
 'weather_delay',
 'nas_delay',
 'security_delay',
 'late_aircraft_delay',
 'cancelled',
 'taxi_in',
 'taxi_out',
 'diverted',
 'iscarrier_delay',
 'isweather_delay',
 'isnas_delay',
 'issecurity_delay',
 'islate_aircraft_delay',
 'delay_type',
 'flight_number',
 'fl_month',
 'fl_day',
 'fl_day_of_year',
 'fl_day_of_week',
 'dep_hour',
 'arr_hour',
 'duration_type',
 'dep_daysection',
 'arr_daysection',
 'fl_season',
 'origin_state',
 'dest_state',
 'origin_airport_vol',
 'dest_airport_vol',
 'carrier_origin_apt_vol',
 'carrier_dest_apt_vol',
 'carrier_origin_apt_pct',
 'carrier_dest_apt_pct',
 'mean_carrier_arr_delay',
 'me

In [34]:
dfF1 = dfF

In [35]:
dfF1 = dfF1.drop([
'carrier_delay',
 'weather_delay',
 'nas_delay',
 'security_delay',
 'late_aircraft_delay',                             
'iscarrier_delay',
 'isweather_delay',
 'isnas_delay',
 'issecurity_delay',
 'islate_aircraft_delay'],axis=1)

In [36]:
total = dfF1.isnull().sum().sort_values(ascending=False)
percent = (dfF1.isnull().sum()/dfF1.isnull().count()).sort_values(ascending=False)
missing_data = pd.concat([total, percent], axis=1, keys=['Total', 'Percent'])
missing_data.head(50)

Total   Percent
delay_type                                     1593560  0.796780
std_carrier_route_month_dow_dayS_arr-delay       92480  0.046240
std_carrier_route_month_dow_dayS_dep-delay       88410  0.044205
arr_delay                                        50903  0.025451
taxi_in                                          46645  0.023322
taxi_out                                         45579  0.022790
dep_delay                                        44306  0.022153
tail_num                                          8873  0.004437
mean_carrier_route_month_dow_dayS_arr-delay       2921  0.001460
median_carrier_route_month_dow_dayS_arr-delay     2921  0.001460
median_carrier_route_month_dow_dayS_dep-delay     2392  0.001196
mean_carrier_route_month_dow_dayS_dep-delay       2392  0.001196
std_carrier_dest_fl-hour_delay                    1739  0.000870
std_carrier_origin_dep-hour_dep_delay             1541  0.000771
std_route_arr_delay_dow                            898  0.000449
std_route_dep_delay_dow                            898  0.000449
std_route_arr_delay_dep_hour                       884  0.000442
std_route_dep_delay_dep_hour                       882  0.000441
std_route_arr_delay_arr_hour                       773  0.000387
std_route_dep_delay_arr_hour                       769  0.000385
std_route_arr_delay_month                           65  0.000032
median_carrier_dest_fl-hour_delay                   64  0.000032
mean_carrier_dest_fl-hour_delay                     64  0.000032
std_route_dep_delay_month                           63  0.000031
median_route_arr_delay_dep_hour                     37  0.000018
mean_route_arr_delay_dep_hour                       37  0.000018
mean_carrier_origin_dep-hour_dep_delay              34  0.000017
median_carrier_origin_dep-hour_dep_delay            34  0.000017
mean_route_dep_delay_dep_hour                       26  0.000013
median_route_dep_delay_dep_hour                     26  0.000013
mean_route_arr_delay_arr_hour                       25  0.000013
median_route_arr_delay_arr_hour                     25  0.000013
median_route_arr_delay_dow                          18  0.000009
mean_route_arr_delay_dow                            18  0.000009
median_route_dep_delay_arr_hour                     12  0.000006
mean_route_dep_delay_arr_hour                       12  0.000006
mean_route_dep_delay_dow                            10  0.000005
median_route_dep_delay_dow                          10  0.000005
mean_route_arr_delay_month                           6  0.000003
median_route_arr_delay_month                         6  0.000003
op_unique_carrier_OH                                 0  0.000000
op_unique_carrier_OO                                 0  0.000000
op_unique_carrier_NK                                 0  0.000000
route_month_weather_delay_pct                        0  0.000000
op_unique_carrier_MQ                                 0  0.000000
op_unique_carrier_DL                                 0  0.000000
dest_month_weather_delay_pct                         0  0.000000
op_unique_carrier_HA                                 0  0.000000
origin_month_weather_delay_pct                       0  0.000000
op_unique_carrier_PT                                 0  0.000000

In [37]:
dfF1 = dfF1[dfF1['delay_type'].notnull()]
dfF1 = dfF1[dfF1['duration_type'].notnull()]

In [38]:
dfF1 = dfF1[dfF1['taxi_in'].notnull()]
dfF1 = dfF1[dfF1['taxi_out'].notnull()]
dfF1 = dfF1[dfF1['dep_delay'].notnull()]
dfF1 = dfF1[dfF1['mean_carrier_route_month_dow_dayS_dep-delay'].notnull()]
dfF1 = dfF1[dfF1['median_carrier_route_month_dow_dayS_dep-delay'].notnull()]


In [39]:
# Keep numerical data only
dfF1 = dfF1.select_dtypes('number')
# Remove Columns with Nans
dfF1 = dfF1.select_dtypes('number').dropna(axis='columns')

In [40]:
y = dfF1.delay_type
df_numeric = dfF1.drop(["delay_type"],axis=1)

from sklearn.feature_selection import VarianceThreshold
# remove features with small variance
vt = VarianceThreshold(0.1)
df_transformed = vt.fit_transform(df_numeric)
selected_columns = df_numeric.columns[vt.get_support()]
# transforming an array back to a data-frame preserves column labels
df_transformed = pd.DataFrame(df_transformed, columns = selected_columns)

In [41]:
# remove highly correlated pairs
df_corr = df_transformed.corr().abs()
indices = np.where(df_corr > 0.9)
indices = [(df_corr.index[x], df_corr.columns[y]) for x, y in zip(*indices)
              if x != y and x < y]
for idx in indices:
    try:
        df_transformed.drop(idx[1], axis = 1, inplace=True)
    except KeyError:
        pass

In [42]:
# forward regression
from sklearn.feature_selection import f_regression, SelectKBest
skb = SelectKBest(f_regression, k=30)
X = skb.fit_transform(df_transformed, y)
X = pd.DataFrame(X,columns=df_transformed.columns[skb.get_support()])
X.columns

Index(['mkt_carrier_fl_num', 'origin_airport_id', 'crs_elapsed_time',
       'taxi_out', 'dep_daysection', 'arr_daysection', 'origin_airport_vol',
       'carrier_origin_apt_vol', 'carrier_origin_apt_pct',
       'mean_carrier_arr_delay_month',
       'mean_carrier_origin_dep-hour_dep_delay',
       'mean_carrier_dest_fl-hour_delay',
       'median_carrier_origin_dep-hour_dep_delay',
       'median_carrier_dest_fl-hour_delay',
       'mean_carrier_route_month_dow_dayS_dep-delay',
       'median_carrier_route_month_dow_dayS_dep-delay',
       'median_carrier_route_month_dow_dayS_arr-delay',
       'mean_route_arr_delay_dep_hour', 'mean_route_arr_delay_arr_hour',
       'median_route_arr_delay_dep_hour', 'median_route_dep_delay_dep_hour',
       'median_route_arr_delay_arr_hour', 'median_route_dep_delay_arr_hour',
       'arr_daysection_carrier_delay_pct', 'arr_daysection_nas_delay_pct',
       'dep_daysection_nas_delay_pct', 'carrier_late_aircraft_delay_pct',
       'carrier_route_month

In [44]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,train_size=0.80,random_state=1,stratify=y)


In [45]:
X_train

mkt_carrier_fl_num  origin_airport_id  crs_elapsed_time  taxi_out  \
216245              4826.0            15016.0              85.0      18.0   
364777              5350.0            11057.0              60.0      26.0   
270008              3940.0            12889.0              95.0      20.0   
187068               830.0            13930.0              94.0      55.0   
298227              3874.0            14576.0             125.0      17.0   
...                    ...                ...               ...       ...   
166217              2599.0            10397.0              71.0      15.0   
50735               4735.0            10627.0             113.0      20.0   
113022               300.0            12478.0             380.0      67.0   
272117              4337.0            12478.0             119.0      37.0   
45434                282.0            14893.0             238.0      19.0   

        dep_daysection  arr_daysection  origin_airport_vol  \
216245             3.0             4.0             18785.0   
364777             2.0             2.0             61809.0   
270008             1.0             1.0             41068.0   
187068             4.0             4.0             98204.0   
298227             2.0             2.0              4734.0   
...                ...             ...                 ...   
166217             2.0             2.0             99995.0   
50735              1.0             1.0              1237.0   
113022             4.0             4.0             31943.0   
272117             2.0             2.0             31943.0   
45434              2.0             4.0             13650.0   

        carrier_origin_apt_vol  carrier_origin_apt_pct  \
216245                   172.0                0.915624   
364777                 24150.0               39.071980   
270008                 17663.0               43.009156   
187068                 18968.0               19.314896   
298227                   188.0                3.971272   
...                        ...                     ...   
166217                 62582.0               62.585129   
50735                    214.0               17.299919   
113022                  3759.0               11.767836   
272117                   112.0                0.350625   
45434                    853.0                6.249084   

        mean_carrier_arr_delay_month  mean_carrier_origin_dep-hour_dep_delay  \
216245                     18.656086                               28.625000   
364777                     13.959031                                5.564528   
270008                      4.447843                                6.393013   
187068                     16.830808                               23.565015   
298227                      1.410759                               10.212121   
...                              ...                                     ...   
166217                      6.636698                               10.326923   
50735                      11.344525                               45.840000   
113022                     15.290937                               21.245902   
272117                      5.594030                               40.821429   
45434                      10.808743                                9.416667   

        mean_carrier_dest_fl-hour_delay  \
216245                        32.776000   
364777                         4.809524   
270008                        30.825939   
187068                        29.151515   
298227                         1.495637   
...                                 ...   
166217                        -0.480769   
50735                          6.779793   
113022                        11.914761   
272117                        21.210526   
45434                         26.719702   

        median_carrier_origin_dep-hour_dep_delay  \
216245                                      -3.0   
364777                                      -3.0   
270008 

In [46]:
#RF
from sklearn.ensemble import RandomForestClassifier

regr = RandomForestClassifier(n_estimators=60, max_depth=10, random_state=0)
regr.fit(X_train,y_train)

RandomForestClassifier(max_depth=10, n_estimators=60, random_state=0)

In [47]:
y_pred=regr.predict(X_test)
y_pred

array([3., 5., 3., ..., 1., 1., 5.])

In [48]:
#Accuracy Score
regr.score(X_test, y_pred)

from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_pred))

#Classification Report
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

#Confusion Matrix
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred))

0.6861461205198898
              precision    recall  f1-score   support

         1.0       0.67      0.43      0.53     21788
         2.0       0.97      0.01      0.02      2667
         3.0       0.73      0.88      0.80     23821
         4.0       0.00      0.00      0.00       160
         5.0       0.66      0.77      0.71     32812

    accuracy                           0.69     81248
   macro avg       0.61      0.42      0.41     81248
weighted avg       0.69      0.69      0.66     81248



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


[[ 9444     0  2963     0  9381]
 [  624    31   589     0  1423]
 [  512     0 20926     0  2383]
 [   66     1    17     0    76]
 [ 3480     0  3985     0 25347]]


In [49]:
pd.Series(y_pred).describe()

count    81248.000000
mean         3.602304
std          1.494640
min          1.000000
25%          3.000000
50%          3.000000
75%          5.000000
max          5.000000
dtype: float64

In [50]:
#NB
from sklearn.naive_bayes import GaussianNB
clf = GaussianNB()


In [51]:
clf.fit(X_train, y_train)

GaussianNB()

In [52]:
y_pred = clf.predict(X_test)

In [53]:
#Accuracy Score
regr.score(X_test, y_pred)

from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_pred))

#Classification Report
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

#Confusion Matrix
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred))

0.5621307601417881
              precision    recall  f1-score   support

         1.0       0.55      0.22      0.31     21788
         2.0       0.08      0.07      0.07      2667
         3.0       0.67      0.78      0.72     23821
         4.0       0.01      0.30      0.02       160
         5.0       0.61      0.68      0.64     32812

    accuracy                           0.56     81248
   macro avg       0.38      0.41      0.35     81248
weighted avg       0.59      0.56      0.55     81248

[[ 4736   579  3651  3037  9785]
 [  304   181   740   181  1261]
 [  855   579 18535   545  3307]
 [   21     1    19    48    71]
 [ 2699   943  4926  2072 22172]]


In [54]:
import xgboost as xgb
from sklearn.metrics import mean_squared_error

data_dmatrix = xgb.DMatrix(data=X.astype(int),label=y.astype(int))

In [55]:
#create train/test split
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X.astype(int), y.astype(int), test_size=0.2, random_state=123)

In [56]:
xg_reg = xgb.XGBRegressor(objective ='reg:squarederror', colsample_bytree = 0.3, learning_rate = 0.1,
                max_depth = 5, alpha = 10, n_estimators = 10)


In [57]:
xg_reg.fit(X_train,y_train)

y_preds = xg_reg.predict(X_test)

In [58]:
rmse = np.sqrt(mean_squared_error(y_test, y_preds))
print("RMSE: %f" % (rmse))

RMSE: 1.814767


In [59]:
#Accuracy Score
regr.score(X_test, y_pred)

from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_pred))

#Classification Report
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

#Confusion Matrix
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred))

0.31323847971642377
              precision    recall  f1-score   support

           1       0.28      0.11      0.16     21948
           2       0.02      0.02      0.02      2630
           3       0.29      0.34      0.32     23847
           4       0.00      0.04      0.00       158
           5       0.41      0.45      0.43     32665

    accuracy                           0.31     81248
   macro avg       0.20      0.19      0.18     81248
weighted avg       0.32      0.31      0.31     81248

[[ 2398   587  7536  1645  9782]
 [  278    54   949   176  1173]
 [ 2464   738  8149  1775 10721]
 [   21     6    48     6    77]
 [ 3454   898 11189  2281 14843]]
